# Generated by Django 3.2.23 on 2023-12-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='side',
            new_name='long',
        ),
    ]
