# Generated by Django 3.2.23 on 2023-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0004_auto_20231218_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='wallet_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
