# Generated by Django 3.2.23 on 2024-04-04 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dydx', '0005_alter_balance_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256)),
                ('action', models.CharField(default='Slow Withdraw', max_length=256)),
                ('status', models.CharField(default='Confirmed', max_length=256)),
                ('amount', models.FloatField()),
                ('transaction', models.CharField(max_length=256)),
                ('fee', models.CharField(default='-', max_length=256)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256)),
                ('market', models.CharField(default='ETH-USD', max_length=256)),
                ('long', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('fee', models.FloatField()),
                ('tradetype', models.CharField(choices=[('Liquidated', 'Liquidated'), ('Market', 'Market')], max_length=256)),
                ('liquidity', models.CharField(choices=[('Maker', 'Maker'), ('Taker', 'Taker')], max_length=256)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256)),
                ('market', models.CharField(default='ETH-USD', max_length=256)),
                ('funding_rate', models.FloatField()),
                ('long', models.BooleanField(default=True)),
                ('payment', models.FloatField()),
                ('ppsition', models.FloatField()),
                ('position_asset', models.CharField(default='ETH', max_length=256)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
