# Generated by Django 3.2.23 on 2024-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0006_historyfunding_historytrades_historytransfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransfers',
            name='transaction_link',
            field=models.CharField(default='https://', max_length=500),
        ),
        migrations.AlterField(
            model_name='historytransfers',
            name='transaction',
            field=models.CharField(max_length=500),
        ),
    ]
