# Generated by Django 3.2.23 on 2024-05-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dydx', '0008_auto_20240518_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makepositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='ETH-USD', max_length=255)),
                ('long', models.BooleanField(default=True)),
                ('size', models.FloatField()),
                ('leverage', models.FloatField()),
                ('realized_PL', models.FloatField()),
                ('average_open', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('uni_wallet', models.CharField(max_length=500)),
                ('dydx_wallet', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('account_leverage', models.FloatField(default=70)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uniswap', models.BooleanField(default=True)),
                ('wallet_address', models.CharField(max_length=500, null=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
