# Generated by Django 3.2.23 on 2024-05-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0009_auto_20240518_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
    ]
