# Generated by Django 3.2.23 on 2024-05-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0012_staking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('uni_wallet', models.CharField(max_length=500)),
                ('dydx_wallet', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staking',
            name='user',
        ),
        migrations.AddField(
            model_name='staking',
            name='telegram_user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegramuser'),
        ),
        migrations.DeleteModel(
            name='Telegram_User',
        ),
    ]
