# Generated by Django 3.2.23 on 2024-05-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0013_auto_20240519_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='Telegram_User',
        ),
        migrations.RemoveField(
            model_name='staking',
            name='telegram_user_id',
        ),
        migrations.AddField(
            model_name='staking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
    ]
