# Generated by Django 3.2.23 on 2024-05-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0014_auto_20240519_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram_user',
            name='user_id',
        ),
    ]
