# Generated by Django 3.2.23 on 2024-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0015_remove_telegram_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staking',
            name='user',
        ),
        migrations.AddField(
            model_name='staking',
            name='telegram_user',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='telegram_user',
            name='user_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
