# Generated by Django 3.2.23 on 2024-05-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0016_auto_20240519_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='staking',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dydx.wallet'),
        ),
    ]
