# Generated by Django 3.2.23 on 2024-05-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0017_staking_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='telegram_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
