# Generated by Django 3.2.23 on 2024-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0018_positions_telegram_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram_user',
            name='dydx_wallet',
        ),
        migrations.AddField(
            model_name='telegram_user',
            name='atomic_wallet',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='telegram_user',
            name='oneinch_wallet',
            field=models.CharField(default='', max_length=500),
        ),
    ]
