# Generated by Django 3.2.23 on 2024-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0019_auto_20240520_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
