# Generated by Django 3.2.23 on 2024-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0020_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staking',
            name='staking_date',
            field=models.IntegerField(),
        ),
    ]
