# Generated by Django 3.2.23 on 2024-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0023_deposit_telegram_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallettype',
            field=models.CharField(choices=[('1Inch', '1Inch'), ('Uniswap', 'Uniswap')], default='Uniswap', max_length=256),
        ),
    ]
