# Generated by Django 3.2.23 on 2024-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0024_deposit_wallettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
