# Generated by Django 3.2.23 on 2024-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0026_remove_deposit_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
