# Generated by Django 3.2.23 on 2024-05-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0028_alter_deposit_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='user_telegram',
            new_name='telegram_user',
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('wallettype', models.CharField(choices=[('1Inch', '1Inch'), ('Uniswap', 'Uniswap')], default='Uniswap', max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dydx.wallet')),
            ],
        ),
    ]
