# Generated by Django 3.2.23 on 2024-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0030_closed_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staking',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
