# Generated by Django 3.2.23 on 2024-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0037_telegram_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_positions',
            name='channel_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='channel_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positions',
            name='channel_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='channel_sent',
            field=models.BooleanField(default=False),
        ),
    ]
