# Generated by Django 3.2.23 on 2024-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0038_auto_20240527_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='channel_edited',
            field=models.BooleanField(default=True),
        ),
    ]
