# Generated by Django 3.2.23 on 2024-05-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0039_positions_channel_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrades',
            name='make_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.makepositions'),
        ),
    ]
