# Generated by Django 3.2.25 on 2024-07-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0040_historytrades_make_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='on_inch_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='deposit',
            name='uniswap_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
    ]
