# Generated by Django 3.2.25 on 2024-07-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0041_auto_20240724_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='telegram_user',
            field=models.CharField(max_length=255),
        ),
    ]
