# Generated by Django 3.2.25 on 2024-07-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0042_alter_deposit_telegram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
    ]
