# Generated by Django 3.2.25 on 2024-07-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0043_alter_deposit_telegram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='on_inch_link',
            new_name='oneinch_link',
        ),
        migrations.AlterField(
            model_name='closed_positions',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
        migrations.AlterField(
            model_name='staking',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dydx.telegram_user'),
        ),
    ]
