# Generated by Django 3.2.25 on 2024-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0044_auto_20240724_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='oneinch_link',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='uniswap_link',
        ),
        migrations.AddField(
            model_name='wallet',
            name='oneinch_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wallet',
            name='uniswap_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
