# Generated by Django 3.2.25 on 2024-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dydx', '0046_alter_staking_telegram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_positions',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
